// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CatalogueItem struct {
	ID     string   `json:"id"`
	Title  string   `json:"title"`
	Uom    string   `json:"uom"`
	Orders []*Order `json:"orders"`
}

type CreateCatalogueItemInput struct {
	Title string `json:"title"`
	Uom   string `json:"uom"`
}

type CreateOrderInput struct {
	UserID    string                      `json:"userId"`
	Positions []*CreateOrderPositionInput `json:"positions"`
}

type CreateOrderPositionInput struct {
	CatalogueItemID string `json:"catalogueItemId"`
	Title           string `json:"title"`
	Quantity        int32  `json:"quantity"`
}

type CreateUserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Mutation struct {
}

type Order struct {
	ID        string           `json:"id"`
	User      *User            `json:"user"`
	Positions []*OrderPosition `json:"positions"`
}

type OrderPosition struct {
	ID            string         `json:"id"`
	CatalogueItem *CatalogueItem `json:"catalogueItem"`
	Quantity      *int32         `json:"quantity,omitempty"`
}

type Query struct {
}

type User struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Email  string   `json:"email"`
	Orders []*Order `json:"orders"`
}
